const properties = [
  {
    name: "Seaside Villa",
    tagline: "Luxury stay by the beach",
    category: "Villa",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    country: "Greece",
    description: "A beautiful villa overlooking the Aegean Sea.",
    price: 500,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    amenities: "WiFi, Pool, Kitchen, Air Conditioning",
  },
  {
    name: "Mountain Cabin",
    tagline: "Escape to the mountains",
    category: "Cabin",
    image: "https://images.unsplash.com/photo-1559099430-b65e5e5440a6",
    country: "Canada",
    description: "Cozy cabin nestled in the Rocky Mountains.",
    price: 200,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    amenities: "Fireplace, Hot Tub, WiFi",
  },
  {
    name: "Urban Apartment",
    tagline: "Modern apartment in the city center",
    category: "Apartment",
    image: "https://images.unsplash.com/photo-1600607681015-8d7cfb0435b2",
    country: "USA",
    description: "Stylish apartment in downtown with a view of the skyline.",
    price: 150,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    amenities: "WiFi, Gym, Parking",
  },
  {
    name: "Countryside Cottage",
    tagline: "Charming retreat in the countryside",
    category: "Cottage",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad",
    country: "UK",
    description: "A cozy cottage surrounded by greenery and open fields.",
    price: 120,
    guests: 3,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    amenities: "Fireplace, Garden, Pet Friendly",
  },
  {
    name: "Beachfront Bungalow",
    tagline: "Private bungalow on the beach",
    category: "Bungalow",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b",
    country: "Thailand",
    description: "Stay steps away from the sand in this serene bungalow.",
    price: 350,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: "WiFi, Beach Access, Air Conditioning",
  },
  {
    name: "Lakeside Lodge",
    tagline: "Tranquil lodge by the lake",
    category: "Lodge",
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1",
    country: "Finland",
    description: "Relax at this peaceful lakeside lodge with sauna.",
    price: 250,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: "WiFi, Sauna, Kayaks",
  },
  {
    name: "City Loft",
    tagline: "Stylish loft in the heart of the city",
    category: "Loft",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    country: "USA",
    description: "Modern loft with high ceilings and a city view.",
    price: 180,
    guests: 4,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: "WiFi, Gym, Rooftop Access",
  },
  {
    name: "Desert House",
    tagline: "Experience the desert landscape",
    category: "House",
    image: "https://images.unsplash.com/photo-1600585154842-50fd8dc4a5c7",
    country: "Morocco",
    description: "Traditional house with stunning desert views.",
    price: 300,
    guests: 5,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: "WiFi, Patio, Air Conditioning",
  },
  {
    name: "Forest Retreat",
    tagline: "Escape to a secluded forest cabin",
    category: "Cabin",
    image: "https://images.unsplash.com/photo-1470165515910-1f4a8cded6d2",
    country: "Sweden",
    description: "Wooden cabin surrounded by lush forest and wildlife.",
    price: 220,
    guests: 4,
    bedrooms: 2,
    beds: 3,
    baths: 1,
    amenities: "Fireplace, BBQ, Outdoor Deck",
  },
  {
    name: "Ski Chalet",
    tagline: "Perfect for winter getaways",
    category: "Chalet",
    image: "https://images.unsplash.com/photo-1549421263-4d7c65eb4b86",
    country: "Switzerland",
    description: "Beautiful chalet with ski-in/ski-out access.",
    price: 550,
    guests: 10,
    bedrooms: 5,
    beds: 6,
    baths: 4,
    amenities: "WiFi, Fireplace, Ski Storage",
  },
  // (Continue similarly for the remaining 20 entries...)
];
